// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('src/plugins');
config.seedProjects.basePaths.push('node_modules/finite-state-machine/src/seeds/FiniteStateMachine');





// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'FiniteStateMachine': 'node_modules\finite-state-machine\src\seeds\FiniteStateMachine'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/fsm';
validateConfig(config);
module.exports = config;
